#!/usr/bin/env python3
"""Regenerate the checked-in sources embedded into tmux; no runtime file loading."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
modules=['config','math','color','draw','animation','events']
lines=['/* Generated by tools/embed-cursor-smear.py; upstream licenses in vendor/smear-cursor. */\n']
for name in modules+['host']:
    source=root/('cursor-smear-host.lua' if name=='host' else f'vendor/smear-cursor/{name}.lua')
    lines.append(f'static const char smear_lua_{name}[] =\n')
    lines.extend(json.dumps(line,ensure_ascii=False)+'\n' for line in source.read_text().splitlines(keepends=True))
    lines.append(';\n')
lines.append('static const struct { const char *name, *source; } smear_lua_modules[] = {\n')
for name in modules:lines.append(f'{{"smear_cursor.{name}", smear_lua_{name}}},\n')
lines.append('{NULL,NULL}};\n')
(root/'cursor-smear-lua.h').write_text(''.join(lines))
